# Generated by Django 5.0.1 on 2024-05-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
