# Generated by Django 5.0.1 on 2024-05-01 12:14

import vendor_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0002_vendor_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(default=vendor_management.models.vendor_code, max_length=20, unique=True),
        ),
    ]
