# Generated by Django 5.0.1 on 2024-05-01 15:43

import vendor_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0003_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(blank=True, default=vendor_management.models.vendor_code, max_length=20, null=True),
        ),
    ]
